import {
    BookMarked,
    Building,
    CalendarClock,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUpDown,
    FileSpreadsheet,
    FileUp,
    HandCoins,
    Handshake,
    PartyPopper,
    LibraryBig,
    Lightbulb,
    LucideIcon,
    PanelLeft,
    Pen,
    Repeat,
    Rocket,
    SquareKanban,
    Bug,
    Gamepad2,
    ExternalLink,
    DollarSign,
    Clock,
    BarChartBig,
    LineChart,
    Plane,
    PieChart,
    Calendar,
    Home,
    Book,
    Layers,
  } from 'lucide-react';
  import {
    AlertTriangle,
    ArrowRight,
    ChevronLeft,
    ChevronRight,
    Command,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    SunMedium,
    Trash,
    User,
    X,
    ChevronDown,
    ChevronUp,
    Users,
    UserPlus2,
    Mail,
    FolderOpen,
    ArchiveRestore,
    Info,
    MessagesSquare,
    Send,
    MessageSquareDashed,
    Lock,
    AlertOctagon,
    ThumbsUp,
    ThumbsDown,
    Clipboard,
  } from 'lucide-react';
  
  export type Icon = LucideIcon;
  
  export const Icons = {
    logo: Command,
    pen: Pen,
    home: Home,
    layers: Layers,
    book: Book,
    dollar: DollarSign,
    bug: Bug,
    calendar: Calendar,
    game: Gamepad2,
    squareKanban: SquareKanban,
    repeat: Repeat,
    clock: Clock,
    pieChart: PieChart,
    close: X,
    plane: Plane,
    rocket: Rocket,
    library: LibraryBig,
    spinner: Loader2,
    building: Building,
    doubleChevronLeft: ChevronsLeft,
    doubleChevronRight: ChevronsRight,
    spreadsheet: FileSpreadsheet,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    chevronUpDown: ChevronsUpDown,
    chevronUp: ChevronUp,
    trash: Trash,
    chartLine: LineChart,
    externalLink: ExternalLink,
    bookMarked: BookMarked,
    sidebarPanel: PanelLeft,
    handshake: Handshake,
    PartyPopper: PartyPopper,
    chat: MessagesSquare,
    lightbulb: Lightbulb,
    calendarClock: CalendarClock,
    handCoins: HandCoins,
    barChart: BarChartBig,
    emptyChat: MessageSquareDashed,
    fileText: FileText,
    page: File,
    media: Image,
    lock: Lock,
    mail: Mail,
    send: Send,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    folderOpen: FolderOpen,
    archiveRestore: ArchiveRestore,
    users: Users,
    addUser: UserPlus2,
    warning: AlertTriangle,
    user: User,
    info: Info,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    alertOctagon: AlertOctagon,
    thumbsUp: ThumbsUp,
    thumbsDown: ThumbsDown,
    clipboard: Clipboard,
    uploadFile: FileUp,
    collapse: ChevronsUpDown,
  };
  